eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
states: TamilNadu, Maharasthra, Madhya Pradesh, Gujurat, Kerala, Andhra Prasdesh, West Bengal, Telugana, Karnataka
server:
  port: ${PORT:${SERVER_PORT:0}}